language: android
sudo: false

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

branches:
  only:
  - master
  - dev

before_install:
  - curl -sSL "https://dl-ssl.google.com/linux/linux_signing_key.pub" | sudo -E apt-key add -
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a ${TRAVIS_ROOT}/etc/apt/sources.list >/dev/null
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt install dpkg
  - sudo apt install google-chrome-stable
  - yes | sdkmanager "platforms;android-27"
  - nvm install 15
  - npm install -g @ionic/cli @angular/cli cordova appcenter-cli
  - export CHROME_BIN=google-chrome
  - google-chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - cd client
  - npm ci

script:
  - npm run ci-test
  - npm run package
  # - ./signbuild.sh
  # - appcenter distribute release \
  #       --group Collaborators \
  #       --file "./artifacts/app-release.apk" \
  #       --release-notes 'App submission via Travis-CI' \
  #       --app Chris/OpenOralBibleClient \
  #       --token "${appcenter_api_token}" \
  #       --quiet

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - CHROME_BIN=google-chrome
  - ANDROID_BUILD_TOOLS=26.0.2